---
- block:
    - name: Ensure Netdata collector configuration directory exists
      ansible.builtin.file:
        path: /etc/netdata/go.d
        state: directory
        owner: root
        group: netdata
        mode: "0750"

    - name: Configure Netdata PgBouncer collector
      ansible.builtin.template:
        src: templates/pgbouncer.conf.j2
        dest: /etc/netdata/go.d/pgbouncer.conf
        owner: root
        group: netdata
        mode: "0640"
      no_log: true
      notify: restart netdata
  ignore_errors: "{{ netdata_install_ignore_errors | default(true) }}"
  when:
    - netdata_install | default(false) | bool
    - pgbouncer_install | default(true) | bool
    - netdata_pgbouncer_collector | default(true) | bool
  tags: netdata_pgbouncer

- name: Remove disabled Netdata PgBouncer collector configuration
  ansible.builtin.file:
    path: /etc/netdata/go.d/pgbouncer.conf
    state: absent
  notify: restart netdata
  ignore_errors: "{{ netdata_install_ignore_errors | default(true) }}"
  when:
    - netdata_install | default(false) | bool
    - not (pgbouncer_install | default(true) | bool and netdata_pgbouncer_collector | default(true) | bool)
  tags: netdata_pgbouncer
